=== JokubasKul/Saityno-paslaugos/1_praktinis_darbas/src/main/java/lt/viko/eif/jkulbokas/Scrap/currencies.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="currencies">
        <xs:complexType>
            <xs:sequence>

                <xs:element name="currency" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="country" type="xs:string"/>
                            <xs:element name="name" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== JokubasKul/Saityno-paslaugos/1_praktinis_darbas/received_currencies.xml
<?xml version="1.0" encoding="UTF-8"?>


<currencies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="currencies.xsd">
	<currency>
		<country>Lithuania</country>
		<name>Euro</name>
	</currency>
	<currency>
		<country>Australia</country>
		<name>Australian dollar</name>
	</currency>
	<currency>
		<country>Iceland</country>
		<name>Icelandic króna</name>
	</currency>
	<currency>
		<country>Indonesia</country>
		<name>Indonesian rupiah</name>
	</currency>
	<currency>
		<country>Hungary</country>
		<name>Hungarian forint</name>
	</currency>
	<currency>
		<country>Ireland</country>
		<name>Euro</name>
	</currency>
	<currency>
		<country>South Korea</country>
		<name>South Korean won</name>
	</currency>
	<currency>
		<country>Liechtenstein</country>
		<name>Swiss franc</name>
	</currency>
	<currency>
		<country>Albania</country>
		<name>Albanian lek</name>
	</currency>
	<currency>
		<country>United Kingdom</country>
		<name>Sterling</name>
	</currency>
</currencies>
